const Koa = require('koa')
const koaStatic = require('koa-static')
const koaBodyParse = require('koa-bodyparser')
const {staticDir, port} = require('./config')
const logger = require('./logger')('server')
const router = require('./router')
const app = new Koa()
app.use(koaStatic(staticDir))
app.use(koaBodyParse())
app.use(router)
app.on('error', err => logger.error(err))
app.listen(port, () => logger.info(`server start on: ${port}`))