const Koa = require('koa')
const koaStatic = require('koa-static')
const koaBodyParse = require('koa-bodyparser')
const logger = require('./logger')('server')
const { port, staticDir } = require('./config')
const router = require('./router')
const app = new Koa()
app.use(koaStatic(staticDir))
app.use(koaBodyParse())
app.use(router)
app.listen(port, () => {
  logger.info(`server is start on ${port}`)
})